
//CreateUser
POST http://localhost:5000/users
Content-Type: application/json

{
    "username" : "admin",
    "password" : "123456",
    "confPassword" : "123456"
}

###
//GetAdmin
GET http://localhost:5000/users

###
GET http://localhost:5000/users/454123da-8557-44fc-b081-1660f062ae5b

###
PATCH http://localhost:5000/users/c4da1634-4130-42be-9cce-6f6ba422af73
Content-Type: application/json

{
    "username": "admin"
}
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username" : "admin",
    "password" : "123456",
    "confPassword" : "123456"
}
###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "123456"   
}

###
GET http://localhost:5000/me
 
###
DELETE  http://localhost:5000/logout
###

GET http://localhost:5000/wisata

###

POST http://localhost:5000/wisata
Content-Type: application/json

{
    "name" : "Pantai Kejawanan",
    "description" : "Pantai Indah",
    "image" : "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pegipegi.com%2Fhotel%2Fbali%2Fpantai_kuta%2F&psig=AOvVaw0QZ3Z4Z4Z4Z4Z4Z4Z4Z4Z4&ust=1629786166594000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjQ4ZqHgvICFQAAAAAdAAAAABAD",
    "price" : 100000,
    "categoryId" : "1",
    "jam_buka" : "08.00",
    "jam_tutup" : "17.00",
    "location"  : "-6.733512661724268, 108.58584415526721",
    "address" : "Jl. Pantai Kejawanan, Kec. Lemahwungkuk, Kota Cirebon, Jawa Barat 45113"
}

###
GET  http://localhost:5000/Category

###
POST http://localhost:5000/category
Content-Type: application/json

{
    "name" : "Majalengka"
}
###

PATCH  http://localhost:5000/category/b2181dd9-c95d-45b0-9cf0-a50436dc595f
Content-Type: application/json

{
    "name": "Cirebon"
}

###

PATCH http://localhost:5000/wisata/1b4a9b2e-3979-4526-b6ac-34018b6befc3
Content-Type: application/json

{
    "name": "Sunyaragi",
    "description": "Test Wisata",
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pegipegi.com%2Fhotel%2Fbali%2Fpantai_kuta%2F&psig=AOvVaw0QZ3Z4Z4Z4Z4Z4Z4Z4Z4Z4&ust=1629786166594000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjQ4ZqHgvICFQAAAAAdAAAAABAD",
    "price": "100000",
    "categoryId": "1"
}

###
GET http://localhost:5000/wisata

###
GET http://localhost:5000/wisata/1b4a9b2e-3979-4526-b6ac-34018b6befc3

###
DELETE http://localhost:5000/wisata/1b4a9b2e-3979-4526-b6ac-34018b6befc3

###
POST http://localhost:5000/kuliner
Content-Type: application/json

{
    "name": "Empal Gentong",
    "description": "Test Kuliner Cirebon Kategori Cirebon",
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pegipegi.com%2Fhotel%2Fbali%2Fpantai_kuta%2F&psig=AOvVaw0QZ3Z4Z4Z4Z4Z4Z4Z4Z4Z4&ust=1629786166594000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjQ4ZqHgvICFQAAAAAdAAAAABAD",
    "price": "100000",
    "nama_restoran" : "H. Apud",
    "jam_buka": "08.00",
    "jam_tutup": "17.00",
    "location": "-6.733512661724268, 108.58584415526721",
    "address": "Jl. Pantai Kejawanan, Kec. Lemahwungkuk, Kota Cirebon, Jawa Barat 45113",

    "categoryId": "1"
}

###
DELETE  http://localhost:5000/kuliner/f850a07c-b030-41f4-8122-5711e87abda6

###
GET http://localhost:5000/kuliner

###
PATCH   http://localhost:5000/tempatkuliner/fb2fa8d4-de38-4eed-bce5-a5afd7b9c6a2
Content-Type: application/json

{
    "name": "Empal Gentong H. Apud",
    "address": "Jl. Raya Cirebon - Indramayu, Kec. Kandanghaur, Kabupaten Indramayu, Jawa Barat 45252",
    "jam_buka": "08.00",
    "detailkulinerId": "1"
}
###
GET  http://localhost:5000/tempatkuliner

###
DELETE   http://localhost:5000/tempatkuliner/9c04b693-3dd4-4031-bfcf-f362d1ee7ca4
