
//CreateUser
POST http://localhost:5000/users
Content-Type: application/json

{
    "username" : "admin",
    "password" : "123456",
    "confPassword" : "123456"
}

###
//GetAdmin
GET http://localhost:5000/users

###
GET http://localhost:5000/users/454123da-8557-44fc-b081-1660f062ae5b

###
PATCH http://localhost:5000/users/c4da1634-4130-42be-9cce-6f6ba422af73
Content-Type: application/json

{
    "username": "admin"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "123456"   
}

###
GET http://localhost:5000/me
 
###
DELETE  http://localhost:5000/logout
###

GET http://localhost:5000/wisata

###

POST http://localhost:5000/wisata
Content-Type: application/json

{
    "name" : "Pantai",
    "description" : "Pantai Indah",
    "image" : "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pegipegi.com%2Fhotel%2Fbali%2Fpantai_kuta%2F&psig=AOvVaw0QZ3Z4Z4Z4Z4Z4Z4Z4Z4Z4&ust=1629786166594000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjQ4ZqHgvICFQAAAAAdAAAAABAD",
    "price" : 100000,
    "categoryId" : "Pantai",

}

###
GET  http://localhost:5000/Category
