GET http://localhost:5000/wisata

###

POST http://localhost:5000/wisata
Content-Type: application/json

{
    "name" : "Batu Lawang",
    "description" : "Wisata ini dekat dengan gempol",
    "image" : "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pegipegi.com%2Fhotel%2Fbali%2Fpantai_kuta%2F&psig=AOvVaw0QZ3Z4Z4Z4Z4Z4Z4Z4Z4Z4&ust=1629786166594000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjQ4ZqHgvICFQAAAAAdAAAAABAD",
    "price" : 100000,
    "categoryId" : "1",
    "jam_buka" : "08.00",
    "jam_tutup" : "17.00",
    "location"  : "-6.733512661724268, 108.58584415526721",
    "address" : "Jl. Pantai Kejawanan, Kec. Lemahwungkuk, Kota Cirebon, Jawa Barat 45113"
}

###
PATCH http://localhost:5000/wisata/1b4a9b2e-3979-4526-b6ac-34018b6befc3
Content-Type: application/json

{
    "name": "Sunyaragi",
    "description": "Test Wisata",
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pegipegi.com%2Fhotel%2Fbali%2Fpantai_kuta%2F&psig=AOvVaw0QZ3Z4Z4Z4Z4Z4Z4Z4Z4Z4&ust=1629786166594000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJjQ4ZqHgvICFQAAAAAdAAAAABAD",
    "price": "100000",
    "categoryId": "1"
}

###
DELETE http://localhost:5000/wisata/1b4a9b2e-3979-4526-b6ac-34018b6befc3

